# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1864, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Train_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Train_Button.setGeometry(QtCore.QRect(20, 20, 251, 91))
        self.Train_Button.setObjectName("Train_Button")
        self.Guess_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Guess_Button.setGeometry(QtCore.QRect(20, 120, 251, 161))
        self.Guess_Button.setObjectName("Guess_Button")
        self.Clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_Button.setGeometry(QtCore.QRect(20, 290, 251, 71))
        self.Clear_Button.setObjectName("Clear_Button")
        self.Preview_CheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.Preview_CheckBox.setGeometry(QtCore.QRect(300, 370, 341, 29))
        self.Preview_CheckBox.setObjectName("Preview_CheckBox")
        self.Eta_DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Eta_DoubleSpinBox.setGeometry(QtCore.QRect(170, 430, 101, 31))
        self.Eta_DoubleSpinBox.setDecimals(2)
        self.Eta_DoubleSpinBox.setSingleStep(0.05)
        self.Eta_DoubleSpinBox.setObjectName("Eta_DoubleSpinBox")
        self.Epochs_SpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.Epochs_SpinBox.setGeometry(QtCore.QRect(170, 480, 101, 31))
        self.Epochs_SpinBox.setObjectName("Epochs_SpinBox")
        self.Eta_Label = QtWidgets.QLabel(self.centralwidget)
        self.Eta_Label.setGeometry(QtCore.QRect(30, 430, 131, 25))
        self.Eta_Label.setObjectName("Eta_Label")
        self.Epochs_Label = QtWidgets.QLabel(self.centralwidget)
        self.Epochs_Label.setGeometry(QtCore.QRect(30, 480, 131, 25))
        self.Epochs_Label.setObjectName("Epochs_Label")
        self.canvasPanel = Painter(self.centralwidget)
        self.canvasPanel.setGeometry(QtCore.QRect(300, 20, 341, 341))
        self.canvasPanel.setFrameShape(QtWidgets.QFrame.Box)
        self.canvasPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.canvasPanel.setObjectName("canvasPanel")
        self.Save_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Save_Button.setGeometry(QtCore.QRect(670, 430, 341, 61))
        self.Save_Button.setObjectName("Save_Button")
        self.Load_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Load_Button.setGeometry(QtCore.QRect(670, 500, 341, 61))
        self.Load_Button.setObjectName("Load_Button")
        self.Activation_Label = QtWidgets.QLabel(self.centralwidget)
        self.Activation_Label.setGeometry(QtCore.QRect(300, 430, 131, 25))
        self.Activation_Label.setObjectName("Activation_Label")
        self.Softmax_CheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.Softmax_CheckBox.setGeometry(QtCore.QRect(300, 480, 261, 29))
        self.Softmax_CheckBox.setObjectName("Softmax_CheckBox")
        self.Architecture_Label = QtWidgets.QLabel(self.centralwidget)
        self.Architecture_Label.setGeometry(QtCore.QRect(300, 530, 131, 25))
        self.Architecture_Label.setObjectName("Architecture_Label")
        self.Activation_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Activation_comboBox.setGeometry(QtCore.QRect(440, 430, 201, 31))
        self.Activation_comboBox.setObjectName("Activation_comboBox")
        self.Activation_comboBox.addItem("")
        self.Activation_comboBox.addItem("")
        self.Activation_comboBox.addItem("")
        self.Activation_comboBox.addItem("")
        self.Activation_comboBox.addItem("")
        self.Architecture_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Architecture_lineEdit.setGeometry(QtCore.QRect(440, 530, 201, 31))
        font = QtGui.QFont()
        font.setKerning(True)
        self.Architecture_lineEdit.setFont(font)
        self.Architecture_lineEdit.setAcceptDrops(True)
        self.Architecture_lineEdit.setAutoFillBackground(False)
        self.Architecture_lineEdit.setMaxLength(32766)
        self.Architecture_lineEdit.setFrame(True)
        self.Architecture_lineEdit.setClearButtonEnabled(False)
        self.Architecture_lineEdit.setObjectName("Architecture_lineEdit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(280, 430, 20, 131))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(650, 430, 20, 131))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Status_Label = QtWidgets.QLabel(self.centralwidget)
        self.Status_Label.setGeometry(QtCore.QRect(80, 584, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Status_Label.setFont(font)
        self.Status_Label.setObjectName("Status_Label")
        self.Output_Label = QtWidgets.QLabel(self.centralwidget)
        self.Output_Label.setGeometry(QtCore.QRect(670, 20, 341, 341))
        font = QtGui.QFont()
        font.setPointSize(120)
        self.Output_Label.setFont(font)
        self.Output_Label.setLineWidth(-1)
        self.Output_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Output_Label.setObjectName("Output_Label")
        self.Bar_0 = Bar(self.centralwidget)
        self.Bar_0.setGeometry(QtCore.QRect(1050, 20, 71, 471))
        self.Bar_0.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_0.setObjectName("Bar_0")
        self.Bar_1 = Bar(self.centralwidget)
        self.Bar_1.setGeometry(QtCore.QRect(1130, 20, 71, 471))
        self.Bar_1.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_1.setObjectName("Bar_1")
        self.Bar_2 = Bar(self.centralwidget)
        self.Bar_2.setGeometry(QtCore.QRect(1210, 20, 71, 471))
        self.Bar_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_2.setObjectName("Bar_2")
        self.Bar_3 = Bar(self.centralwidget)
        self.Bar_3.setGeometry(QtCore.QRect(1290, 20, 71, 471))
        self.Bar_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_3.setObjectName("Bar_3")
        self.Bar_4 = Bar(self.centralwidget)
        self.Bar_4.setGeometry(QtCore.QRect(1370, 20, 71, 471))
        self.Bar_4.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_4.setObjectName("Bar_4")
        self.Bar_9 = Bar(self.centralwidget)
        self.Bar_9.setGeometry(QtCore.QRect(1770, 20, 71, 471))
        self.Bar_9.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_9.setObjectName("Bar_9")
        self.Bar_6 = Bar(self.centralwidget)
        self.Bar_6.setGeometry(QtCore.QRect(1530, 20, 71, 471))
        self.Bar_6.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_6.setObjectName("Bar_6")
        self.Bar_7 = Bar(self.centralwidget)
        self.Bar_7.setGeometry(QtCore.QRect(1610, 20, 71, 471))
        self.Bar_7.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_7.setObjectName("Bar_7")
        self.Bar_5 = Bar(self.centralwidget)
        self.Bar_5.setGeometry(QtCore.QRect(1450, 20, 71, 471))
        self.Bar_5.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_5.setObjectName("Bar_5")
        self.Bar_8 = Bar(self.centralwidget)
        self.Bar_8.setGeometry(QtCore.QRect(1690, 20, 71, 471))
        self.Bar_8.setFrameShape(QtWidgets.QFrame.Box)
        self.Bar_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bar_8.setObjectName("Bar_8")
        self.StatusLamp = StatusLamp(self.centralwidget)
        self.StatusLamp.setGeometry(QtCore.QRect(10, 590, 61, 20))
        self.StatusLamp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StatusLamp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StatusLamp.setObjectName("StatusLamp")
        self.Label_1 = QtWidgets.QLabel(self.centralwidget)
        self.Label_1.setGeometry(QtCore.QRect(1130, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_1.setFont(font)
        self.Label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_1.setObjectName("Label_1")
        self.Label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_2.setGeometry(QtCore.QRect(1210, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_2.setFont(font)
        self.Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_2.setObjectName("Label_2")
        self.Label_3 = QtWidgets.QLabel(self.centralwidget)
        self.Label_3.setGeometry(QtCore.QRect(1290, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_3.setFont(font)
        self.Label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_3.setObjectName("Label_3")
        self.Label_4 = QtWidgets.QLabel(self.centralwidget)
        self.Label_4.setGeometry(QtCore.QRect(1370, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_4.setFont(font)
        self.Label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_4.setObjectName("Label_4")
        self.Label_5 = QtWidgets.QLabel(self.centralwidget)
        self.Label_5.setGeometry(QtCore.QRect(1450, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_5.setFont(font)
        self.Label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_5.setObjectName("Label_5")
        self.Label_6 = QtWidgets.QLabel(self.centralwidget)
        self.Label_6.setGeometry(QtCore.QRect(1610, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_6.setFont(font)
        self.Label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_6.setObjectName("Label_6")
        self.Label_7 = QtWidgets.QLabel(self.centralwidget)
        self.Label_7.setGeometry(QtCore.QRect(1690, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_7.setFont(font)
        self.Label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_7.setObjectName("Label_7")
        self.Label_8 = QtWidgets.QLabel(self.centralwidget)
        self.Label_8.setGeometry(QtCore.QRect(1530, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_8.setFont(font)
        self.Label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_8.setObjectName("Label_8")
        self.Label_9 = QtWidgets.QLabel(self.centralwidget)
        self.Label_9.setGeometry(QtCore.QRect(1770, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_9.setFont(font)
        self.Label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_9.setObjectName("Label_9")
        self.Label_0 = QtWidgets.QLabel(self.centralwidget)
        self.Label_0.setGeometry(QtCore.QRect(1050, 500, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Label_0.setFont(font)
        self.Label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_0.setObjectName("Label_0")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Activation_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MNIST"))
        self.Train_Button.setText(_translate("MainWindow", "Train Network"))
        self.Guess_Button.setText(_translate("MainWindow", "Make A Guess"))
        self.Clear_Button.setText(_translate("MainWindow", "Clear"))
        self.Preview_CheckBox.setText(_translate("MainWindow", "Show Processing"))
        self.Eta_Label.setText(_translate("MainWindow", "Learning Rate"))
        self.Epochs_Label.setText(_translate("MainWindow", "Epochs"))
        self.Save_Button.setText(_translate("MainWindow", "Save State"))
        self.Load_Button.setText(_translate("MainWindow", "Load State"))
        self.Activation_Label.setText(_translate("MainWindow", "Activation"))
        self.Softmax_CheckBox.setText(_translate("MainWindow", "Softmax"))
        self.Architecture_Label.setText(_translate("MainWindow", "Architecture"))
        self.Activation_comboBox.setItemText(0, _translate("MainWindow", "Sigmoid"))
        self.Activation_comboBox.setItemText(1, _translate("MainWindow", "tanh"))
        self.Activation_comboBox.setItemText(2, _translate("MainWindow", "ReLU"))
        self.Activation_comboBox.setItemText(3, _translate("MainWindow", "Leaky ReLU"))
        self.Activation_comboBox.setItemText(4, _translate("MainWindow", "Linear"))
        self.Architecture_lineEdit.setText(_translate("MainWindow", "784,10"))
        self.Status_Label.setText(_translate("MainWindow", "Status"))
        self.Output_Label.setText(_translate("MainWindow", "0"))
        self.Label_1.setText(_translate("MainWindow", "1"))
        self.Label_2.setText(_translate("MainWindow", "2"))
        self.Label_3.setText(_translate("MainWindow", "3"))
        self.Label_4.setText(_translate("MainWindow", "4"))
        self.Label_5.setText(_translate("MainWindow", "5"))
        self.Label_6.setText(_translate("MainWindow", "7"))
        self.Label_7.setText(_translate("MainWindow", "8"))
        self.Label_8.setText(_translate("MainWindow", "6"))
        self.Label_9.setText(_translate("MainWindow", "9"))
        self.Label_0.setText(_translate("MainWindow", "0"))

from bar import Bar
from painter import Painter
from statuslamp import StatusLamp
